name: Build Web-XGrammar

on:
  workflow_dispatch:
  pull_request:
  push:
  # branches:
  #   - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          cd ..

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Web-XGrammar
        run: |
          cd web
          npm install
          npm run build

      - name: Run Tests
        run: |
          npm test
