name: Build Web-XGrammar

on:
  workflow_dispatch:
  pull_request:
  push:
  # branches:
  #   - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-14, macos-15-intel]
        python: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
        exclude:
          - os: macos-15-intel
            python: '3.13'
            # The reason for the exclusion is that pytorch distribution
            # can't be found by pip on macos-15-intel with python 3.13.
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Web-XGrammar
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          cd ..
          cd web
          npm install
          npm run build

      - name: Run Tests
        run: |
          npm test
