name: Build Web-XGrammar

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-dev cmake ninja-build

      - name: Setup Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          echo "source $(pwd)/emsdk_env.sh" >> $GITHUB_ENV

      - name: Build Web-XGrammar
        run: |
          cd web
          npm install
          mkdir -p build
          cd build
          emcmake cmake ../.. \
            -DBUILD_PYTHON_BINDINGS=OFF \
            -DXGRAMMAR_BUILD_PYTHON_BINDINGS=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_FLAGS="-O3 -DCOMPILE_WASM_RUNTIME -DXGRAMMAR_LOG_CUSTOMIZE=1"
          emmake make -j$(nproc)
          cd ..
          npx rollup -c

      - name: Run Tests
        run: |
          cd web
          npm test
