name: Build Docs

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy_docs:
    name: Deploy Docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Installing dependencies
        run: |
          python -m pip install -r docs/requirements.txt
          gem install jekyll jekyll-remote-theme

      - name: Build Docs
        run: |
          ./scripts/local_deploy_site.sh
