name: test build on riscv

on:
  workflow_dispatch:
  pull_request:
  push:
  # branches:
  #   - main

jobs:
  riscv:
    name: ubuntu-24.04-riscv
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test build on riscv
        uses: uraimo/run-on-arch-action@v3
        with:
          arch: riscv64
          distro: ubuntu24.04
          run: |
            sudo apt install python
            echo "set(XGRAMMAR_BUILD_CXX_TESTS ON)" >> cmake/config.cmake
            echo "set(XGRAMMAR_ENABLE_INTERNAL_CHECK ON)" >> cmake/config.cmake
            python -m pip install --upgrade pip
            pip install -v ".[test]"
